package GUI;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer Customer
 */
public class GUItest extends javax.swing.JFrame {

    /**
     * Creates new form GUItest
     */
    public GUItest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideTabs = new javax.swing.JTabbedPane();
        tabSadness = new javax.swing.JTextField();
        tabSorrow = new javax.swing.JScrollPane();
        sorrowList = new javax.swing.JList<>();
        tabTab3 = new javax.swing.JScrollPane();
        tab3Textarea = new javax.swing.JTextArea();
        chatPane = new javax.swing.JScrollPane();
        chatBoxHistory = new javax.swing.JTextArea();
        chatBoxSend = new javax.swing.JTextField();
        chatButtonSend = new javax.swing.JButton();
        gamePane = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        menuDropdownHelp = new javax.swing.JMenu();
        helpOptionShortcuts = new javax.swing.JMenuItem();
        helpOptionAbout = new javax.swing.JMenuItem();
        helpSeparator = new javax.swing.JPopupMenu.Separator();
        helpOptionNobodycame = new javax.swing.JMenuItem();
        menuDropdownSettings = new javax.swing.JMenu();
        menuOptionResolution = new javax.swing.JMenuItem();
        menuOptionLightmode = new javax.swing.JMenuItem();
        menuOptionDarkmode = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Untitled Chatroom Application v0.6.8.99");

        tabSadness.setEditable(false);
        tabSadness.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tabSadness.setText("imagine having a sleep schedule");
        sideTabs.addTab("sadness", tabSadness);

        sorrowList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hello", "my name", "is Elder", "Price", "hah gottem" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tabSorrow.setViewportView(sorrowList);

        sideTabs.addTab("sorrow", tabSorrow);

        tab3Textarea.setColumns(20);
        tab3Textarea.setLineWrap(true);
        tab3Textarea.setRows(5);
        tab3Textarea.setText("not sure what to put here but there ya go... you can edit this panel, too! :p");
        tab3Textarea.setWrapStyleWord(true);
        tabTab3.setViewportView(tab3Textarea);

        sideTabs.addTab("tab3", tabTab3);

        chatBoxHistory.setEditable(false);
        chatBoxHistory.setColumns(20);
        chatBoxHistory.setLineWrap(true);
        chatBoxHistory.setRows(5);
        chatBoxHistory.setText("[xXN05cOp3rXx]: \"your really good at chess!\"\n[Hikaru_Nakamura]: \"you䀙re*\"\n[xXN05cOp3rXx]: \"wow this application is really poorly coded\"");
        chatPane.setViewportView(chatBoxHistory);

        chatBoxSend.setToolTipText("");
        chatBoxSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBoxSendActionPerformed(evt);
            }
        });

        chatButtonSend.setText("-->");
        chatButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonSendActionPerformed(evt);
            }
        });

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("aaaaand this is where I'd put a game.\n\n\n\n\n\n\t\t\tIF I HAD ONE");
        gamePane.setViewportView(jTextArea3);

        menuDropdownHelp.setText("Help");
        menuDropdownHelp.setToolTipText("");
        menuDropdownHelp.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
                menuDropdownHelpMenuDragMouseEntered(evt);
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });

        helpOptionShortcuts.setText("Shortcuts");
        menuDropdownHelp.add(helpOptionShortcuts);

        helpOptionAbout.setText("About");
        helpOptionAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpOptionAboutActionPerformed(evt);
            }
        });
        menuDropdownHelp.add(helpOptionAbout);
        menuDropdownHelp.add(helpSeparator);

        helpOptionNobodycame.setText("But nobody came.");
        helpOptionNobodycame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpOptionNobodycameActionPerformed(evt);
            }
        });
        menuDropdownHelp.add(helpOptionNobodycame);

        menuBar.add(menuDropdownHelp);

        menuDropdownSettings.setText("Settings");

        menuOptionResolution.setText("Resolution");
        menuDropdownSettings.add(menuOptionResolution);

        menuOptionLightmode.setText("Light Mode");
        menuDropdownSettings.add(menuOptionLightmode);

        menuOptionDarkmode.setText("Dark Mode");
        menuDropdownSettings.add(menuOptionDarkmode);

        menuBar.add(menuDropdownSettings);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatPane, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chatBoxSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatButtonSend))
                    .addComponent(gamePane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideTabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chatPane, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chatButtonSend)
                    .addComponent(chatBoxSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDropdownHelpMenuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_menuDropdownHelpMenuDragMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDropdownHelpMenuDragMouseEntered

    private void helpOptionAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpOptionAboutActionPerformed
        // TODO add your handling code here:
        showMessageDialog(null, "This software was created by:\n\nRam Kammari\nArt Olsen\nNathaniel Potgiesser\nDiego Rivera\nFelix Tang");
    }//GEN-LAST:event_helpOptionAboutActionPerformed

    private void helpOptionNobodycameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpOptionNobodycameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpOptionNobodycameActionPerformed

    private void chatBoxSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatBoxSendActionPerformed
        // TODO add your handling code here:
        if (!chatBoxSend.getText().equals("")){
            chatBoxHistory.append("\n[User]: \"" + chatBoxSend.getText() + "\"");
            chatBoxSend.setText("");
        }
        chatBoxSend.requestFocus();
    }//GEN-LAST:event_chatBoxSendActionPerformed

    private void chatButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonSendActionPerformed
        // TODO add your handling code here:
        chatBoxSendActionPerformed(evt);
    }//GEN-LAST:event_chatButtonSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUItest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUItest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUItest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUItest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUItest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatBoxHistory;
    private javax.swing.JTextField chatBoxSend;
    private javax.swing.JButton chatButtonSend;
    private javax.swing.JScrollPane chatPane;
    private javax.swing.JScrollPane gamePane;
    private javax.swing.JMenuItem helpOptionAbout;
    private javax.swing.JMenuItem helpOptionNobodycame;
    private javax.swing.JMenuItem helpOptionShortcuts;
    private javax.swing.JPopupMenu.Separator helpSeparator;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDropdownHelp;
    private javax.swing.JMenu menuDropdownSettings;
    private javax.swing.JMenuItem menuOptionDarkmode;
    private javax.swing.JMenuItem menuOptionLightmode;
    private javax.swing.JMenuItem menuOptionResolution;
    private javax.swing.JTabbedPane sideTabs;
    private javax.swing.JList<String> sorrowList;
    private javax.swing.JTextArea tab3Textarea;
    private javax.swing.JTextField tabSadness;
    private javax.swing.JScrollPane tabSorrow;
    private javax.swing.JScrollPane tabTab3;
    // End of variables declaration//GEN-END:variables
}
